// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyF3WycNjnKNkBqLtLWWdvr8eMTgeKM58',
    appId: '1:522991060175:web:a7e260081569fde937a3ba',
    messagingSenderId: '522991060175',
    projectId: 'meetra-meet',
    authDomain: 'meetra-meet.firebaseapp.com',
    storageBucket: 'meetra-meet.firebasestorage.app',
    measurementId: 'G-0EJDT2PHZX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhefsdPNJyFsBo-nWt8LSTvRpyBAOB-EE',
    appId: '1:522991060175:android:cb919624f7819ef637a3ba',
    messagingSenderId: '522991060175',
    projectId: 'meetra-meet',
    storageBucket: 'meetra-meet.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REPLACE_WITH_YOUR_IOS_API_KEY',
    appId: 'REPLACE_WITH_YOUR_IOS_APP_ID',
    messagingSenderId: '522991060175',
    projectId: 'meetra-meet',
    storageBucket: 'meetra-meet.firebasestorage.app',
    iosBundleId: 'com.example.meetraMeet',
  );
}
